name: WhatToCook Project CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Use Node.js version 18.15.0
        uses: actions/setup-node@v3
        with:
          node-version: '18.15.0'
      
      - name: Install dependencies
        run: npm install
      
      - name: Build
        run: npm run build


